name: rc_car_controller
description: RC Car Bluetooth Controller
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Add your logo here
  assets:
    - assets/images/


# Configure launcher icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0a0e27"
  adaptive_icon_foreground: "assets/images/logo.png"